name: Build Project

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    name: Build in Container
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: europe-west2-docker.pkg.dev/gen-lang-client-0059571033/dev-images/gridtest-dev:1.0.1
      credentials:
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure CMake
        run: cmake -S . -B build-container-Debug

      - name: Build with CMake
        run: cmake --build build-container-Debug
